GET http://localhost:4550 HTTP/1.1
content-type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJmZXJndXNvbmFkbWluNUBnbWFpbC5jb20iLCJmaXJzdE5hbWUiOiJGZXJndXNvbiIsImxhc3ROYW1lIjoiSXlhcmEiLCJ0eXBlIjoiY2FzaGllciIsImlzQWRtaW4iOmZhbHNlLCJ1cGRhdGVkQXQiOiIyMDE5LTEyLTI4VDA0OjU0OjEzLjgwMVoiLCJjcmVhdGVkQXQiOiIyMDE5LTEyLTI4VDA0OjU0OjEzLjgwMVoiLCJpYXQiOjE1Nzc1MDg4NTMsImV4cCI6MTU3NzU5NTI1M30.g76yREfHGtNuNuRIAEHKmWW6LljJdFA6HYRjQhlTJV8"
}
1200000000